server:
  port: 6161
logging:
  level:
    com:
      iluwatar:
        health:
          check: DEBUG
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true
  h2:
    console:
      enabled: true
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

health:
  check:
    timeout: 10
    cache:
      evict:
        interval: 60000
cpu:
  system:
    load:
      threshold: 95.0
  process:
    load:
      threshold: 70.0
  load:
    average:
      threshold: 10.0
retry:
  backoff:
    period: 2000
  max:
    attempts: 3
memory:
  usage:
    threshold: 0.8
