fun main() {
    Goblin.printStatus()
    Wizard.castSpell(Goblin::changeSize)
    Goblin.printStatus()
    Wizard.castSpell(Goblin::changeVisibility)
    Goblin.printStatus()
    Wizard.undoLastSpell()
    Goblin.printStatus()
    Wizard.undoLastSpell()
    Goblin.printStatus()
    Wizard.redoLastSpell()
    Goblin.printStatus()
    Wizard.redoLastSpell()
    Goblin.printStatus()
}