import org.slf4j.LoggerFactory

private val log = LoggerFactory.getLogger("main")
fun main() {
    log.info("Printing out eagerly initialized multiton contents")
    log.info("KHAMUL={}", Nazgul.getInstance(NazgulName.KHAMUL))
    log.info("MURAZOR={}", Nazgul.getInstance(NazgulName.MURAZOR))
    log.info("DWAR={}", Nazgul.getInstance(NazgulName.DWAR))
    log.info("JI_INDUR={}", Nazgul.getInstance(NazgulName.JI_INDUR))
    log.info("AKHORAHIL={}", Nazgul.getInstance(NazgulName.AKHORAHIL))
    log.info("HOARMURATH={}", Nazgul.getInstance(NazgulName.HOARMURATH))
    log.info("ADUNAPHEL={}", Nazgul.getInstance(NazgulName.ADUNAPHEL))
    log.info("REN={}", Nazgul.getInstance(NazgulName.REN))
    log.info("UVATHA={}", Nazgul.getInstance(NazgulName.UVATHA))
    log.info("Printing out enum-based multiton contents")
    log.info("KHAMUL={}", NazgulEnum.KHAMUL)
    log.info("MURAZOR={}", NazgulEnum.MURAZOR)
    log.info("DWAR={}", NazgulEnum.DWAR)
    log.info("JI_INDUR={}", NazgulEnum.JI_INDUR)
    log.info("AKHORAHIL={}", NazgulEnum.AKHORAHIL)
    log.info("HOARMURATH={}", NazgulEnum.HOARMURATH)
    log.info("ADUNAPHEL={}", NazgulEnum.ADUNAPHEL)
    log.info("REN={}", NazgulEnum.REN)
    log.info("UVATHA={}", NazgulEnum.UVATHA)
}