package baas.model

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import kotlinx.serialization.Serializable

@Serializable
@DynamoDBTable(tableName = "persons")
data class Person(
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    var id: String? = null,
    @DynamoDBAttribute(attributeName = "firstName")
    var firstName: String? = null,
    @DynamoDBAttribute(attributeName = "lastName")
    var lastName: String? = null,
    @DynamoDBAttribute(attributeName = "address")
    var address: Address? = null
)